export const SET_LAYOUT_SEARCH_OPEN = "SET_LAYOUT_SEARCH_OPEN";
export const SET_LAYOUT_CART_OPEN = "SET_LAYOUT_CART_OPEN";
export const SET_LAYOUT_MENU_OPEN = "SET_LAYOUT_MENU_OPEN";

export const SET_LAYOUT_RESET = "SET_LAYOUT_RESET";
